- name: User
  include_tasks:
    file: users.yml
- name: Packages
  include_tasks:
    file: packages.yml
- name: Localization
  include_tasks:
    file: localization.yml
- name: Installing Atom and Plugins
  include_tasks:
    file: atom.yml
- name: Preparing projects to work on...
  include: projects.yml
  when: "'projects.yml' is file"
- name: Rebooting...
  shell: shutdown -r now
