- name: Hold grub (workaround)
  dpkg_selections: 
    name: "{{ item }}"
    selection: hold
  with_items: "{{ grub_packages }}"
- name: apt update
  apt: update_cache=yes
- name: apt upgrade
  apt: upgrade=dist
# Install pre-reqs for Ansible install
- name: Installing packages
  apt:
    name: "{{ debian_packages }}"
    state: present  
- locale_gen: name={{ locale }} state=present
- command: /usr/sbin/update-locale LANG={{ locale }} LC_ALL={{ locale }}
- lineinfile:
    dest: /etc/default/console-setup
    state: present
    regexp: "{{ item.regexp}}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^FONTFACE=', line: 'FONTFACE="{{ fontface }}"'}
  notify: dpkg-reconfigure console-setup
- file: src=/usr/share/zoneinfo/{{ timezone }} dest=/etc/localtime state=link
- lineinfile: dest=/etc/timezone state=present line={{ timezone }} regexp='.*' create=yes
  notify: dpkg-reconfigure tzdata
- group: name=wheel state=present
- lineinfile:
    dest: /etc/sudoers
    state: present
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    regexp: '^%wheel'
    validate: 'visudo -cf %s'
- user:
    name: '{{ login }}'
    password: '{{ password }}'
    comment: '{{ gecos }}'
    state: present
    shell: '/bin/bash'
    groups:
      - wheel
    append: yes
    createhome: yes
- shell: shutdown -r now
