- name: Localization
  include_tasks:
    file: localization.yml
- name: User
  include_tasks:
    file: users.yml
- name: Packages
  include_tasks:
    file: packages.yml
- name: Installing Atom and Plugins
  include_tasks:
    file: atom.yml
- name: Preparing projects to work on...
  include: "{{ item }}"
  with_first_found:
    - files:
        - projects.yml
      skip: true
# Since reboot will cause shared folders unavailable, whe don't want it...
# - name: Rebooting...
#   shell: shutdown -r now
