- name: Creating new group 'wheel'
  group: name=wheel state=present
- name: Adding group 'wheel' to /etc/sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    regexp: '^%wheel'
    validate: 'visudo -cf %s'
- name: Add new user '{{ gecos }}' ({{ login }})
  user:
    name: '{{ login }}'
    password: '{{ password }}'
    comment: '{{ gecos }}'
    state: present
    shell: '/bin/bash'
    groups:
      - wheel
    append: yes
    createhome: yes
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
    force: no